# -*- coding: utf-8 -*-
"""greedy_best_first.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VQbhEjMP6a6QgVXqANxuF0R0W615utIL
"""

from queue import PriorityQueue

# Fungsi untuk algoritma Greedy Search
def greedy_search(graph, start, goal):
    frontier = PriorityQueue()  # Antrian prioritas untuk menyimpan simpul yang akan dieksplorasi
    frontier.put(start, 0)  # Menambahkan simpul awal ke dalam antrian dengan nilai prioritas 0
    explored = set()  # Set untuk menyimpan simpul yang sudah dieksplorasi

    while not frontier.empty():
        current_node = frontier.get()  # Mengambil simpul dengan nilai prioritas terendah dari antrian

        if current_node == goal:
            print("Simpul tujuan sudah ditemukan!")
            return True  # Mengembalikan True jika simpul tujuan sudah ditemukan

        explored.add(current_node)  # Menandai simpul saat ini sebagai sudah dieksplorasi

        for neighbor in graph[current_node]:
            if neighbor not in explored:
                priority = heuristic[neighbor]  # Menggunakan nilai heuristik untuk menentukan prioritas
                frontier.put(neighbor, priority)  # Menambahkan simpul tetangga ke dalam antrian dengan nilai prioritas heuristik

    print("Simpul tujuan tidak ditemukan!")
    return False  # Mengembalikan False jika simpul tujuan tidak ditemukan

    # Daftar heuristik untuk setiap simpul
heuristic = {
    'A': 9,
    'B': 4,
    'C': 2,
    'D': 5,
    'E': 3,
    'S': 7,
    'G': 0
}

# Graf (dalam bentuk daftar kejadian)
graph = {
    'S': {'A', 'E'},
    'A': {'B', 'C'},
    'B': {'D'},
    'C': {'G'},
    'D': {'G'},
    'E': {'D'}
}

# Titik awal dan tujuan
start_node = 'S'
goal_node = 'G'

# Panggil fungsi greedy search
greedy_search(graph, start_node, goal_node)